force-app/main/default/objects/WeatherCity__c/WeatherCity__c.object-meta.xml
<CustomObject>
    <label>Weather City</label>
    <nameField>
        <label>WeatherCity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WeatherCity__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The State that the city resides in</description>
    <label>State</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherCityController.cls
public with sharing class WeatherCityController {
    //Could choose to instead remove inaccessible fields but just did this more explicitly for now
    public static void createWeatherCity(WeatherCity__c wc) {
        if (Schema.sObjectType.WeatherCity__c.isCreateable() &&
            Schema.sObjectType.WeatherCity__c.fields.Location__Latitude__s.isCreateable() &&
            Schema.sObjectType.WeatherCity__c.fields.Location__Longitude__s.isCreateable() &&
            Schema.sObjectType.WeatherCity__c.fields.Name.isCreateable() &&
            Schema.sObjectType.WeatherCity__c.fields.State__c.isCreateable()){
            
            insert wc;
        }
    }

    public static List<WeatherCity__c> retrieveCities(){
        return [SELECT Id, Name, Location__Latitude__s, Location__Longitude__s, State__c FROM WeatherCity__c WITH SECURITY_ENFORCED];
    }
}